[package]
name = "git-syncd"
version = "0.1.0"
edition = "2024"
authors = ["Auto Sync <auto@example.com>"]
description = "Lightweight git-based folder synchronizer daemon"
license = "MIT"

[dependencies]
anyhow = "1"
camino = { version = "1.2", features = ["serde1"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
crossbeam-channel = "0.5"
ctrlc = "3"
directories = "5"
globset = "0.4"
notify = "6.1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

[dev-dependencies]
tempfile = "3"

[profile.release]
strip = true
lto = "thin"
codegen-units = 1
