name: Delete Branch After Merge

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    if: >-
      ${{ github.event.pull_request.merged == true &&
          github.event.pull_request.head.repo.full_name == github.repository &&
          github.event.pull_request.head.ref != 'main' &&
          github.event.pull_request.head.ref != 'develop' &&
          github.event.pull_request.head.ref != 'dev' &&
          !startsWith(github.event.pull_request.head.ref, 'release-please--') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Delete source branch
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.payload.pull_request.head.ref;
            core.info(`Deleting merged branch ${branch}`);
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${branch}`,
            });
