name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all --all-features --locked

      - name: Build release binary
        run: cargo build --release --all-features --locked

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Lint shell installer
        run: shellcheck scripts/install.sh

      - name: Setup PowerShell
        uses: actions/setup-pwsh@v2

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force

      - name: Analyze PowerShell scripts
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Import-Module PSScriptAnalyzer
          $issues = Invoke-ScriptAnalyzer -Path scripts/install.ps1 -Recurse -Severity Error
          if ($issues) {
            $issues | Format-List
            throw 'PSScriptAnalyzer reported errors'
          }
