name: Promote Develop to Main

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  fast-forward-main:
    name: Fast-forward main from develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure main is ancestor
        id: ancestor
        run: |
          git fetch origin main
          if git merge-base --is-ancestor origin/main HEAD; then
            echo "ff-possible=true" >> "$GITHUB_OUTPUT"
          else
            echo "ff-possible=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Push fast-forward to main
        if: steps.ancestor.outputs.ff-possible == 'true'
        run: |
          git push origin HEAD:main

      - name: Report skipped fast-forward
        if: steps.ancestor.outputs.ff-possible != 'true'
        run: |
          echo "main has diverged; manual intervention required" >> "$GITHUB_STEP_SUMMARY"
          exit 1
